language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-28
    - extra-android-m2repository

script: echo '<?xml version="1.0" encoding="utf-8"?><resources><string name="google_maps_key"></string></resources>' > mobile/src/main/res/values/placeholder_maps_key.xml
script: ./gradlew build
script: ./gradlew test
