language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-28
    - extra-android-m2repository

script: ./gradlew build
script: ./gradlew test
